### PR TITLE
Colm/tweaks

### PR DESCRIPTION
**Pull request by ColmBhandal**
## Summary

This PR includes a number of changes to improve the test data and fix bugs.

## Details

- Extended word meaning pairs
  - Added additional word meaning pairs to improve the test data
- Normalized type column to singular case
  - Corrected the type column to use singular case consistently
- Generalized spatial
  - Made the spatial test more flexible by providing a new random letter from A-Z each time the test is restarted
- Ignored pycache
  - Added pycache to the .gitignore file
- Added error handling code in reasoning
  - Added print statements to help debug problems with question generation
- Fixed a typo
  - Replaced a dot with a comma
- Made boolean more explicit
  - Improved the code by making boolean more explicit

### CODE REVIEW

**Review by redg25 — APPROVED** [review]

**Review by redg25 — APPROVED** [review]

**Review by redg25 — APPROVED** [review]

**Review by redg25 — APPROVED** [review]

**Review by redg25 — APPROVED** [review]

**Review by redg25 — APPROVED** [review]

**Review by redg25 — COMMENTED** [review]
In the real test, I think there is only the letter R.
Plus, when I tried your chnanges, I got the letter M which actually always ends up in the same rotation so it doesn't make sense.

**Comment by redg25** [comment]
Sorry, I am not too familiar with PR. I wanted to find a way to only merge the commit I approved but didn't succeed. I tried to merge on a different branch to see what happened and as I suspected all commits got merge.

**Comment by ColmBhandal** [comment]
> In the real test, I think there is only the letter R. Plus, when I tried your chnanges, I got the letter M which actually always ends up in the same rotation so it doesn't make sense.

Yep I think you're right... I made some tweaks. I reverted back to just the letter R in particular. Will add another PR

**Comment by ColmBhandal** [comment]
I'll open another PR. The best way to proceed is as follows:

1. I open the PR
2. You can either make edits to my branch, or ask me to make them
3. When you're happy, you approve and merge the whole thing into master

Alternatively, you might not be happy with some changes and in that case we can just leave it :)

**Pull request merged**
